### ISSUE TITLE
Adding CartoDB Static Maps

### ISSUE THREAD

**Issue by auremoser** [katydecorah/staticmapmaker#10]
Hey Katy! Would it be o.k. if I forked your repo and added the [CartoDB static maps API](http://docs.cartodb.com/cartodb-platform/maps-api.html#static-maps-api)? I don't want to be presumptuous with your repo though, so I thought I'd ask before submitting a PR.

**Comment by katydecorah** [comment]
Hi @auremoser, please do! I've been trying to add as many as possible, but there's only so much time on the weekend :wink:
