### ISSUE TITLE
UI for adding custom markers

### ISSUE THREAD

**Issue by peterqliu** [katydecorah/staticmapmaker#16]
Like this one, from the docs: 

https://api.tiles.mapbox.com/v4/examples.map-zr0njcqy/url-https%3A%2F%2Fmapbox.com%2Fguides%2Fimg%2Fpages%2Frocket.png(-76.9,38.9)/-76.9,38.9,15/100x100.png?access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g

**Comment by katydecorah** [comment]
@peterqliu I already gotchuuuuuuuuuu

![image](https://cloud.githubusercontent.com/assets/2180540/8343455/795d69f2-1aa3-11e5-9cd1-5f101935a4e3.png)

![image](https://cloud.githubusercontent.com/assets/2180540/8343438/5b635b1e-1aa3-11e5-9f35-8c8bed76feee.png)

**Comment by peterqliu** [comment]
:clap: :clap:
