### ISSUE TITLE
Marker size options

### ISSUE THREAD

**Issue by jsnmrs** [katydecorah/staticmapmaker#4]
The default marker size options are strange: **tiny**, **small**, **mid**

Consider changing them to **small**, **medium**, **large**. It's easier to understand and Google's strange naming conventions can be hidden from the user.

![marker-size](https://cloud.githubusercontent.com/assets/1215760/2883615/12b3091a-d49e-11e3-8923-5cef9db76ebd.png)

**Comment by katydecorah** [comment]
great idea, fixed! thanks!
