### ISSUE TITLE
Simple typo in generated HTML for MapBox

### ISSUE THREAD

**Issue by rhewitt22** [katydecorah/staticmapmaker#6]
After toggling to use the MapBox API the generated HTML has an `alt` attribute that mentions Google Maps rather than MapBox

```
<img src="http://api.tiles.mapbox.com/v3/examples.map-zr0njcqy/-73.75,42.65,13/600x300.png" alt="Google Map of -73.75,42.65">
```

Great work!

**Comment by katydecorah** [comment]
@rhewitt22 thanks so much!
