### ISSUE TITLE
Can a marker be added to the map at a point different than the center

### ISSUE THREAD

**Issue by wnordmann** [katydecorah/staticmapmaker#7]
I would like to add a marker to the map somewhere other than center.  This would be great in the situation where the map is centered on a city or major intersection and the marker is on a separate point of interest.  

I would be willing to implement this in a fork but I am having a little trouble with the build process.

**Comment by katydecorah** [comment]
Absolutely @wnordmann! I'm assuming you want this for the Google API? I've been meaning to push this - I'll have it up in a few minutes.

Also, I should really make this repo more contributor-friendly. Thanks for your input! :smile:

**Comment by wnordmann** [comment]
Thanks for adding the markers, that's perfect.  I am still interested in
build instructions so I can learn more about Jekyll.

-William Nordmann
